export const Messages = {
    PLS_ENTER_INFO: "Vui lòng nhập thông tin",
    INVALID_EMAIL: "Email không đúng định dạng",
    INVALID_PASSWORD: "Mật khẩu phải có ít nhất 6 ký tự",
    INVALID_NAME: "Tên phải có ít nhất 3 ký tự",
    EMAIL_NOT_EMPTY: "Email không được để trống",
    PASSWORD_NOT_EMPTY: "Mật khẩu không được để trống",
    NAME_NOT_EMPTY: "Tên không được để trống",
    INVALID_CREDENTIALS: "Email hoặc mật khẩu không chính xác",
    LOGIN_SUCCESS: "Đăng nhập thành công",
    TOKEN_NOT_EMPTY: "Token không được để trống",
    INVALID_TOKEN: "Token đã hết hạn hoặc không hợp lệ",
    REFRESH_TOKEN_SUCCESS: "Refresh token thành công",
    REGISTER_SUCCESS: "Đăng ký thành công! Vui lòng kiểm tra email để nhận mã OTP xác thực",
    EMAIL_ALREADY_REGISTERED: "Email này đã được đăng ký",
    HAVE_ERROR: "Có lỗi xảy ra, vui lòng thử lại sau",
};